name: Release Docs
on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install mkdocs-minify-plugin
      - run: cp ./docker-compose.yml ./docs
      - run: mkdir ./docs/schema
      - run: curl https://raw.githubusercontent.com/enofex/naikan-model/main/src/main/resources/bom-1.0.schema.json --output ./docs/schema/bom-1.0.schema.json
      - run: mkdocs gh-deploy --force
